apiVersion: v1
kind: ConfigMap
metadata:
  name: fb-service-token-cache-env-{{ .Values.environmentName }}
  namespace: formbuilder-platform-{{ .Values.environmentName }}
data:
  RAILS_ENV: "production"
  RAILS_SERVE_STATIC_FILES: "false"
  FB_ENVIRONMENT_SLUG: "{{ .Values.environmentName }}"
  SERVICE_TOKEN_CACHE_TTL: "60"
  RAILS_LOG_TO_STDOUT: "true"
