apiVersion: v1
kind: Secret
metadata:
  name: fb-service-token-cache-app-secrets-{{ .Values.environmentName }}
type: Opaque
data:
  secret_key_base: {{ .Values.secret_key_base }}
  sentry_dsn: {{ .Values.sentry_dsn }}
