kind: Service
apiVersion: v1
metadata:
  name: "fb-service-token-cache-svc-{{ .Values.environmentName }}"
  labels:
    app: "fb-service-token-cache-{{ .Values.environmentName }}"
    appGroup: "fb-service-token-cache"
spec:
  ports:
    # TODO: internal https-only
  - port: 80
    name: http
    targetPort: 3000
  selector:
    app: "fb-service-token-cache-{{ .Values.environmentName }}"
